# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Cloud Hosted Real-Time Data Services for the Geosciences"

description: "CHORDS Portal User Documentation"
  
url: "http://ncar.github.io/chords_portal"
baseurl: "/chords_portal"

github_username:  ncar/chords_portal

email: "chords at eol dot ucar dot edu"

organization: National Center for Atmospheric Research

# Build settings
markdown: kramdown
highlighter: rouge

sass:
   sass_dir: assets/stylesheets

