app:
  build: .
  command: ./chords_start.sh
  volumes:
    - .:/app
    - ./chords_log/:/chords_log
  ports:
    - "3000:3000"
  links:
    - mysql

mysql:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
  ports:
    - "3306"

