default: &default
  host:           'influxdb'
  port:           8086
  # time_precision ns causes influxer to parse a date/time string before
  # writing the point.
  time_precision: 'ns'
  
development:
  <<: *default
  database: 'chords_ts_development'
  
test:
  <<: *default
  database: chords_ts_test
  
production:
  <<: *default
  database: chords_ts_production
  